### PR TITLE
fix change in the items being sent

### LINKED ISSUE #17: New item bug in reorderable
Several users reported a serious bug that caused any new questions to appear at the top of the list to which they were added. They should have appeared at the bottom. I believe that this is because your component is storing state without properly handling componentWillReceiveProps.

Could you please add handling for received props that re-creates the state if the list of items has changed? 

I have done an emergency disabling of the reordering code in mwater-form-designer for now.

### PR DESCRIPTION
**Pull request by broncha**
fixes #17

### CODE REVIEW

File: src/reorderable/ReorderableListComponent.coffee [hunk 1]
```diff
@@ -25,6 +25,11 @@ class ReorderableListComponent extends React.Component
       dropItem: null
     }
 
+  componentWillReceiveProps: (nextProps) ->
+    if nextProps.items.length != @state.initialOrder.length
```
Comment (grassick) [inline src/reorderable/ReorderableListComponent.coffee]: I'm afraid this won't work in all cases. If the items are reordered outside of the component, this will not refresh the state.
